language: node_js

script:
  - npm run build
  - npm run export
  - touch out/.nojekyll
  - echo "tododeploy.com" > out/CNAME

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: out
  on:
    branch: master